# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Xsolla WebView (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Xsolla WebView (iOS)
#  pod 'SwiftUIWebView', '~> 1.0.7'
  
end

target 'Xsolla WebView (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Xsolla WebView (macOS)
#  pod 'SwiftUIWebView', '~> 1.0.7'
  
end
